definitions:
  api.SetValueRequest:
    properties:
      key:
        type: string
      ttl:
        type: integer
      value: {}
    required:
    - key
    - value
    type: object
info:
  contact: {}
paths:
  /delete/{key}:
    delete:
      description: delete key-value pair by key
      parameters:
      - description: Key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Delete key-value pair
      tags:
      - key-value store
  /get/{key}:
    get:
      description: get value associated with the key
      parameters:
      - description: Key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get value by key
      tags:
      - key-value store
  /set:
    post:
      consumes:
      - application/json
      description: Set a key-value pair in the store with an optional TTL (Time To
        Live) in seconds. If TTL is not specified, a default value of 60 seconds is
        used.
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.SetValueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Set key-value pair
      tags:
      - key-value store
swagger: "2.0"
